name: Build Pull Request

on:
  push:
    branches:
    - mc/* # MC version updates
    - pr/* # PR rebases
    - solar # Solar
  pull_request:
    branches:
    - 2.x
    - mc/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore Gradle cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 16
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build --stacktrace
  deploy:
    name: Build and upload
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/solar'
    needs: build
    steps:
    - name: Checkout Git repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore Gradle cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 16
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build publish --stacktrace
      env:
        ORG_GRADLE_PROJECT_solarRepoUsername: ${{ secrets.MAVEN_CD_USER }}
        ORG_GRADLE_PROJECT_solarRepoPassword: ${{ secrets.MAVEN_CD_PASS }}
    - name: Archive plugin jars on GitHub
      uses: actions/upload-artifact@master
      with:
        name: EssentialsX plugin jars
        path: jars/
